# spring 配置
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://122.152.221.117:3306/thirteen?autoReconnect=true
      &useUnicode=true
      &createDatabaseIfNotExist=true
      &characterEncoding=utf8
      &allowMultiQueries=true
      &useSSL=false
      &failOverReadOnly=false
      &serverTimezone=CTT
    username: root
    password: GoGP8De3jMy&
    # hikari数据库连接池
    hikari:
      pool-name: Auth_HikariCP
      # 最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: on
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      connection-test-query: SELECT 1
  # JPA配置
  jpa:
    # 数据库方言
    database-platform: org.hibernate.dialect.MySQL5Dialect
    # 项目启动时是否执行ddl
    generate-ddl: on
    # 是否显示sql
    show-sql: on
    # 设置数据库类型
    database: mysql
    hibernate:
      # 自动建表
      ddl-auto: update
    properties:
      hibernate:
        # sql格式
        show_sql: true
        # sql格式
        format_sql: true
